# Sui Move Package Upgrade Capabilities
# This file tracks upgrade capabilities across different networks

[environments.devnet]
upgrade_cap = "0x2569fb819d4a2e782cd8148845044683bd72510aa67fef10b27f10ff989d65ac"
package_id = "0x4184a9b9fd7fa32f11e106e32fae64cc439b4d8ccda79bffe1a7ddfdc9646d09"
network_rpc = "https://fullnode.devnet.sui.io:443"
created_at = "2026-01-14T00:13:12.543Z"

[environments.localnet]
upgrade_cap = "0x485ba1922b737ce93a2724efb36befd0308465f943a17fb489551914ebefa81f"
package_id = "0x4eb4263c46ce0e31c01e0f078d0b061bd2af65523cc6e49bd78950ae8db15fa8"
network_rpc = "http://127.0.0.1:9000"
created_at = "2026-01-20T01:32:08.973Z"

